### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by youmi-zym** [Caoang327/fwd_code#1]
Hi @Caoang327,
Thanks for your great job! I'd like to know when will you release the code. Thanks sincerely.

**Comment by kir5810** [comment]
Hello
@Caoang327 @crockwell, @jcjohnson
Thanks for your work. Any news on the source code? Or any plans

**Comment by yusukefukuju** [comment]
Me too @Caoang327

**Comment by Caoang327** [comment]
Hi,
sorry for the late response.
We are supposed to release the majority of the code. 

Let me know if you have more questions.
