### ISSUE TITLE
The results by the code do not match the reported results

### ISSUE THREAD

**Issue by tmanh** [Caoang327/fwd_code#2]
Hi, I tried to run the pre-trained model provided in the repository, but the result is worse than the results reported in the paper (PSNR: ~14, SSIM: ~0.55, LPIPS: ~0.385). The synthesized images look very similar to the pictures in the paper. So, I don't know what is the problem.

![output_view_000013](https://user-images.githubusercontent.com/18414646/189495747-b320c0e2-bedd-42a7-af78-e4950349ccb9.png)

**Comment by Caoang327** [comment]
Hi, sorry for the late response.

Which Pytorch3D version are you using? The current pretrained model is only for Pytorch3d v0.4. 
There is a major change in pytorch3d after v0.4, which changes the rendering for non-square images.

**Comment by tmanh** [comment]
Thank you so much! I already changed to Pytorch3D v0.4 to fix this problem.
